### ISSUE TITLE
How to start using these?

### ISSUE THREAD

**Issue by rolocampusano** [kevalsakhiya/real-estate_scrapers#1]
Hi!

I'm moving to Montreal in a few months and I want to start collecting sales data to, eventually, buy something in the city. I am looking for scraping solutions and I found this repo. Could you please point me to some resources to familiarize myself with the tools and help me get started with your scrapers? I am happy to contribute to them after :)

Thanks!

**Comment by kevalsakhiya** [comment]
I wrote the scraper using scrapy (you can install it by **pip install scrapy**, here you can find the documentation https://docs.scrapy.org/en/latest/.
It may have other dependencies as well, I'll add requirement.txt when u get chance. For now just comment pipeline setting from settings.py (pipeline contains the code to store the data to mongodb)
Run the scraper using **scrapy crawl centris**

**Comment by rolocampusano** [comment]
thank you :)
